### ISSUE TITLE
Error deploying Stemcell

### ISSUE THREAD

**Issue by kennetham** [Azure/bosh#3]
After running `bosh deploy micro_bosh.yml` I am getting this error while creating VM.

Please advise.

```log
Verifying stemcell...
File exists and readable                                     OK
Verifying tarball...
Read tarball                                                 OK
Manifest exists                                              OK
Stemcell image file                                          OK
Stemcell properties                                          OK

Stemcell info
-------------
Name:    bosh-azure-hyperv-ubuntu-trusty-go_agent
Version: 0000

  Started deploy micro bosh
  Started deploy micro bosh > Unpacking stemcell. Done (00:00:07)
  Started deploy micro bosh > Uploading stemcell. Done (00:31:17)
  Started deploy micro bosh > Creating VM from bosh-image-5726d8f0-c7a9-49b6-98a5-036c96b3fe24log writing failed. can't be called from trap context
/var/lib/gems/2.1.0/gems/bosh_azure_cpi-1.2807.0/lib/cloud/azure/helpers.rb:56:in `cloud_error': Failed to create instance: create vm failed: only generation of JSON objects or arrays allowed (Bosh::Clouds::CloudError)
/var/lib/gems/2.1.0/gems/json_pure-1.8.2/lib/json/common.rb:223:in `generate'
/var/lib/gems/2.1.0/gems/json_pure-1.8.2/lib/json/common.rb:223:in `generate'
/var/lib/gems/2.1.0/gems/json_pure-1.8.2/lib/json/common.rb:470:in `JSON'
/var/lib/gems/2.1.0/gems/bosh_azure_cpi-1.2807.0/lib/cloud/azure/vm_manager.rb:24:in `create'
/var/lib/gems/2.1.0/gems/bosh_azure_cpi-1.2807.0/lib/cloud/azure/cloud.rb:98:in `block in create_vm'
/var/lib/gems/2.1.0/gems/bosh_common-1.2807.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/lib/gems/2.1.0/gems/bosh_azure_cpi-1.2807.0/lib/cloud/azure/cloud.rb:94:in `create_vm'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:243:in `create_vm'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:123:in `block in create'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:85:in `step'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:122:in `create'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:98:in `block in create_deployment'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:92:in `with_lifecycle'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:98:in `create_deployment'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/cli/commands/micro.rb:179:in `perform'
/var/lib/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/command_handler.rb:57:in `run'
/var/lib/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/runner.rb:56:in `run'
/var/lib/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/runner.rb:16:in `run'
/var/lib/gems/2.1.0/gems/bosh_cli-1.2807.0/bin/bosh:7:in `<top (required)>'
/usr/local/bin/bosh:23:in `load'
/usr/local/bin/bosh:23:in `<main>'
/var/lib/gems/2.1.0/gems/bosh_azure_cpi-1.2807.0/lib/cloud/azure/helpers.rb:56:in `cloud_error'
/var/lib/gems/2.1.0/gems/bosh_azure_cpi-1.2807.0/lib/cloud/azure/vm_manager.rb:103:in `rescue in create'
/var/lib/gems/2.1.0/gems/bosh_azure_cpi-1.2807.0/lib/cloud/azure/vm_manager.rb:13:in `create'
/var/lib/gems/2.1.0/gems/bosh_azure_cpi-1.2807.0/lib/cloud/azure/cloud.rb:98:in `block in create_vm'
/var/lib/gems/2.1.0/gems/bosh_common-1.2807.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/lib/gems/2.1.0/gems/bosh_azure_cpi-1.2807.0/lib/cloud/azure/cloud.rb:94:in `create_vm'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:243:in `create_vm'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:123:in `block in create'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:85:in `step'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:122:in `create'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:98:in `block in create_deployment'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:92:in `with_lifecycle'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:98:in `create_deployment'
/var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/cli/commands/micro.rb:179:in `perform'
/var/lib/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/command_handler.rb:57:in `run'
/var/lib/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/runner.rb:56:in `run'
/var/lib/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/runner.rb:16:in `run'
/var/lib/gems/2.1.0/gems/bosh_cli-1.2807.0/bin/bosh:7:in `<top (required)>'
/usr/local/bin/bosh:23:in `load'
/usr/local/bin/bosh:23:in `<main>'
	from /var/lib/gems/2.1.0/gems/bosh_azure_cpi-1.2807.0/lib/cloud/azure/cloud.rb:119:in `rescue in block in create_vm'
	from /var/lib/gems/2.1.0/gems/bosh_azure_cpi-1.2807.0/lib/cloud/azure/cloud.rb:95:in `block in create_vm'
	from /var/lib/gems/2.1.0/gems/bosh_common-1.2807.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
	from /var/lib/gems/2.1.0/gems/bosh_azure_cpi-1.2807.0/lib/cloud/azure/cloud.rb:94:in `create_vm'
	from /var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:243:in `create_vm'
	from /var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:123:in `block in create'
	from /var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:85:in `step'
	from /var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:122:in `create'
	from /var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:98:in `block in create_deployment'
	from /var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:92:in `with_lifecycle'
	from /var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/deployer/instance_manager.rb:98:in `create_deployment'
	from /var/lib/gems/2.1.0/gems/bosh_cli_plugin_micro-1.2807.0/lib/bosh/cli/commands/micro.rb:179:in `perform'
	from /var/lib/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/command_handler.rb:57:in `run'
	from /var/lib/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/runner.rb:56:in `run'
	from /var/lib/gems/2.1.0/gems/bosh_cli-1.2807.0/lib/cli/runner.rb:16:in `run'
	from /var/lib/gems/2.1.0/gems/bosh_cli-1.2807.0/bin/bosh:7:in `<top (required)>'
	from /usr/local/bin/bosh:23:in `load'
	from /usr/local/bin/bosh:23:in `<main>'
```

**Comment by AbelHu** [comment]
Could you paste the run.log in your folder where you run the command "bosh deploy micro_bosh.yml" if you are using the generated config?

**Comment by kennetham** [comment]
Hi @AbelHu apologies for the late reply. Let me grab the log and update here by today. Thank you.

**Comment by kennetham** [comment]
@AbelHu  It's pretty long
https://gist.github.com/kennetham/60b3a84d06a1d4b9293d

**Comment by AbelHu** [comment]
You can see below logs in your log file. You do not provide valid tenant_id, client_id and client_secret.

I, [2015-06-17T12:45:37.168398 #43078] [create_vm(bm-06ca466c-5b45-46b4-9060-725cad5992db, ...)]  INFO -- : execute command azure login -u <> -p <> --tenant <> --service-principal --json

I, [2015-06-17T12:46:24.834444 #43078] [create_vm(bm-06ca466c-5b45-46b4-9060-725cad5992db, ...)]  INFO -- : Unable to acquire token due to error of: Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: a58ff333-fb97-4310-ac7a-993833d0e360\r\nCorrelation ID: 35063ab5-3ef2-4c9e-9db7-b9b944b712df\r\nTimestamp: 2015-06-17 12:46:15Z","error_codes":[70002,50012],"timestamp":"2015-06-17 12:46:15Z","trace_id":"a58ff333-fb97-4310-ac7a-993833d0e360","correlation_id":"35063ab5-3ef2-4c9e-9db7-b9b944b712df","submit_url":null,"context":null}
login command failed

**Comment by kennetham** [comment]
@AbelHu I did, I actually masked those for security purposes. I did provide a `tenant_id` which was taken from `azure config mode arm` am I right?

**Comment by AbelHu** [comment]
Could you execute below commands manually in your VM and then find the solution by following the error prompt?
1. azure config mode arm
2. azure login -u <> -p <> --tenant <> --service-principal

**Comment by kennetham** [comment]
Yup sure I'll try that later tonight. I don't have my machine with me at the moment. Thank you, I'll ping back with the results.

**Comment by kennetham** [comment]
There is an error downloading and installing v0.3.19.
`E: Version '0.3.19' for 'dokku' was not found`

**Comment by kennetham** [comment]
Am I able to delete the service-principal or retrieve the password from `azure-cli`? I think you are right, the password doesn't match, but I have no idea why. Now I can't set a new application etc. Please advise

**Comment by AbelHu** [comment]
You can delete the service-principal and recreate it again.

**Comment by kennetham** [comment]
Do you mind if I ask, what is the command to delete? I tried something else which looked like a delete, but I kind of got an error.

**Comment by AbelHu** [comment]
You need to find the Application Object Id when you created the service principle. Use below command to delete it.

azure ad app delete <object-id>
